verbose: false
instrumentation:
  root: "./build"
  excludes: ["**/test/**", "**/coverage/**"]
  include-all-sources: true
  default-excludes: true
reporting:
  print: summary
  reports:
    - html
    - text
    - lcov
  dir: ./build/coverage
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]   
